-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: cs_entity_revisions.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE cs_entity_revisions (
  cser_id SERIAL NOT NULL,
  cser_entity_id INT NOT NULL,
  cser_text TEXT NOT NULL,
  cser_actor BIGINT NOT NULL,
  cser_timestamp TIMESTAMPTZ NOT NULL,
  cser_deleted SMALLINT DEFAULT 0 NOT NULL,
  PRIMARY KEY(cser_id)
);

CREATE INDEX cser_entity_id ON cs_entity_revisions (cser_entity_id, cser_timestamp);
