-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: cs_entities.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE cs_entities (
  cse_id SERIAL NOT NULL,
  cse_type SMALLINT NOT NULL,
  cse_assoc_page_id INT NOT NULL,
  cse_parent_id INT DEFAULT NULL,
  cse_title TEXT DEFAULT NULL,
  cse_block_name TEXT DEFAULT NULL,
  cse_author_actor BIGINT NOT NULL,
  cse_last_editor_actor BIGINT DEFAULT NULL,
  cse_created TIMESTAMPTZ NOT NULL,
  cse_modified TIMESTAMPTZ NOT NULL,
  cse_deleted SMALLINT DEFAULT 0 NOT NULL,
  PRIMARY KEY(cse_id)
);

CREATE INDEX cse_assoc_page_id ON cs_entities (cse_assoc_page_id, cse_type);

CREATE INDEX cse_parent_id ON cs_entities (cse_parent_id);

CREATE INDEX cse_author_actor ON cs_entities (cse_author_actor);
