-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: cs_entities.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cs_entities (
  cse_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cse_type SMALLINT UNSIGNED NOT NULL,
  cse_assoc_page_id INTEGER UNSIGNED NOT NULL,
  cse_parent_id INTEGER UNSIGNED DEFAULT NULL,
  cse_title BLOB DEFAULT NULL,
  cse_block_name BLOB DEFAULT NULL,
  cse_author_actor BIGINT UNSIGNED NOT NULL,
  cse_last_editor_actor BIGINT UNSIGNED DEFAULT NULL,
  cse_created BLOB NOT NULL,
  cse_modified BLOB NOT NULL,
  cse_deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX cse_assoc_page_id ON /*_*/cs_entities (cse_assoc_page_id, cse_type);

CREATE INDEX cse_parent_id ON /*_*/cs_entities (cse_parent_id);

CREATE INDEX cse_author_actor ON /*_*/cs_entities (cse_author_actor);
