-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: cs_entity_revisions.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cs_entity_revisions (
  cser_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cser_entity_id INTEGER UNSIGNED NOT NULL,
  cser_text BLOB NOT NULL,
  cser_actor BIGINT UNSIGNED NOT NULL,
  cser_timestamp BLOB NOT NULL,
  cser_deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX cser_entity_id ON /*_*/cs_entity_revisions (cser_entity_id, cser_timestamp);
