-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: cs_entity_revisions.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cs_entity_revisions (
  cser_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  cser_entity_id INT UNSIGNED NOT NULL,
  cser_text MEDIUMBLOB NOT NULL,
  cser_actor BIGINT UNSIGNED NOT NULL,
  cser_timestamp BINARY(14) NOT NULL,
  cser_deleted TINYINT(1) DEFAULT 0 NOT NULL,
  INDEX cser_entity_id (cser_entity_id, cser_timestamp),
  PRIMARY KEY(cser_id)
) /*$wgDBTableOptions*/;
