-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: cs_entities.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cs_entities (
  cse_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  cse_type SMALLINT UNSIGNED NOT NULL,
  cse_assoc_page_id INT UNSIGNED NOT NULL,
  cse_parent_id INT UNSIGNED DEFAULT NULL,
  cse_title VARBINARY(255) DEFAULT NULL,
  cse_block_name VARBINARY(255) DEFAULT NULL,
  cse_author_actor BIGINT UNSIGNED NOT NULL,
  cse_last_editor_actor BIGINT UNSIGNED DEFAULT NULL,
  cse_created BINARY(14) NOT NULL,
  cse_modified BINARY(14) NOT NULL,
  cse_deleted TINYINT(1) DEFAULT 0 NOT NULL,
  INDEX cse_assoc_page_id (cse_assoc_page_id, cse_type),
  INDEX cse_parent_id (cse_parent_id),
  INDEX cse_author_actor (cse_author_actor),
  PRIMARY KEY(cse_id)
) /*$wgDBTableOptions*/;
